export const ACTION = {
  RETURN: "RETURN",
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
  EDIT_TODO: "EDIT_TODO",
  COMPLETE_TODO: "COMPLETE_TODO",
  TOGGLE_ALL: "TOGGLE_ALL",
  CLEAR_COMPLETED: "CLEAR_COMPLETED",
  UPDATE_CREATE_FIELD: "UPDATE_CREATE_FIELD",
  CHANGE_VISIBILITY_FILTER: "CHANGE_VISIBILITY_FILTER"
}

export const APP = {
  ALL_TODOS: "ALL_TODOS",
  ACTIVE_TODOS: "ACTIVE_TODOS",
  COMPLETED_TODOS: "COMPLETED_TODOS"
}
